import { useRouter } from 'next/router';
import Head from 'next/head';

import Header from './Header';
import Footer from './Footer';

type LayoutProps = {
  children: React.ReactNode;
  title: string;
};

const Layout = ({ children, title }: LayoutProps) => {
  const router = useRouter();

  return (
    <>
      <Head>
        <title>Matsuri | {title}</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <div>
        <Header />
        <main>{children}</main>
        {router.pathname !== '/sign-in' && router.pathname !== '/sign-up' && <Footer />}
      </div>
    </>
  );
};

export default Layout;
