import Head from 'next/head';

import Header from './Header';
import Footer from './Footer';

type LayoutProps = {
  children: React.ReactNode;
  title: string;
};

const Layout = ({ children, title }: LayoutProps) => {
  return (
    <>
      <Head>
        <title>Matsuri</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <div>
        <Header title={title} />
        <main>{children}</main>
        {title !== 'Sign In' && title !== 'Sign Up' && <Footer />}
      </div>
    </>
  );
};

export default Layout;
